[project]
name = "nas-res"
version = "0.1.0"
description = "Plotting results for NAS"
authors = [
    {name = "Roberto Del Prete", email = "roberto.delprete@example.com"},
]
dependencies = [
    "pandas>=2.0.0",
    "matplotlib>=3.0.0",
]
requires-python = ">=3.8"

[tool.pdm]
package-type = "library"
