from .vocabulary import convolution_layer_vocabulary, activation_functions_vocabulary, upsampling_layer_vocabulary, pooling_layer_vocabulary, head_vocabulary, skip_connection_layer_vocabulary
from .vocabulary import layer_parameters, parameter_vocabulary 
